@startuml

state 欲界 {
    [*] --> 近行定
}



state 安止定or禅那 {
    
    state 色界 {
        state 初禅 : 寻、伺、喜、乐、一心
        state 二禅 : 净、喜、乐、一心
        state 三禅 : 舍、念、慧、乐、一心
        state 四禅 : 不苦、不乐、舍、念、一心
        初禅 --> 二禅
        二禅 --> 三禅
        三禅 --> 四禅
    }



    state 无色界 {
        空无边处 --> 识无边处
        识无边处 --> 无所想处
        无所想处 --> 非想非非想处
    }
}

state 四果 : 声闻
state 四果 : 四沙门果

state 四果 {
    state 须陀洹果 : 入流
    state 须陀洹果 : 七轮回
    state 须陀洹果 : 贤人

    state 斯陀含果 : 一来
    state 斯陀含果 : 一轮回

    state 阿那含果 : 无还
    state 阿那含果 : 不生于欲界

    state 阿罗汉果 : 无生
    state 阿罗汉果 : 解脱生死

    须陀洹果 --> 斯陀含果
    斯陀含果 --> 阿那含果 
    阿那含果 --> 阿罗汉果
}

state 譬支佛 : 缘觉
state 阿伽陀 : 菩萨

四果 --> 譬支佛
譬支佛 --> 阿伽陀

近行定 --> 初禅
四禅 --left--> 空无边处

不净观 --right--> 初禅
不净观 --right--> 近行定

出入息定 --right--> 安止定or禅那
出入息定 --right--> 近行定

内观 ----> 四果
出入息定 ----> 四果
安止定or禅那 ----> 四果
@enduml